version: 2
updates:
  # Enable version updates for npm (backend)
  - package-ecosystem: "npm"
    directory: "/apps/backend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "joachimaross"
    assignees:
      - "joachimaross"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
    versioning-strategy: "increase"
    # Group minor and patch updates together
    groups:
      nestjs:
        patterns:
          - "@nestjs/*"
      prisma:
        patterns:
          - "@prisma/*"
          - "prisma"
      testing:
        patterns:
          - "@types/*"
          - "jest"
          - "supertest"
          - "ts-jest"

  # Enable version updates for npm (web)
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "joachimaross"
    assignees:
      - "joachimaross"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react*"
      next:
        patterns:
          - "next"

  # Enable version updates for npm (mobile)
  - package-ecosystem: "npm"
    directory: "/apps/mobile"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "joachimaross"
    assignees:
      - "joachimaross"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "mobile"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "ci"
    labels:
      - "ci"
      - "dependencies"
