version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jacameno
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    command: npm run start:dev
    volumes:
      - ./backend:/app
    ports:
      - '3001:3000'

volumes:
  db_data:
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/jacameno
    depends_on:
      - db
volumes:
  db_data:
