[build]
  command = "npm run build"
  publish = "dist"
  functions = "dist/functions"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200

[context.production]
  environment = { NODE_ENV = "production", LOG_LEVEL = "info", SENTRY_DSN = "your_production_sentry_dsn_here", REDIS_URL = "your_production_redis_url_here" }

[context.deploy-preview]
  environment = { NODE_ENV = "development", LOG_LEVEL = "debug", SENTRY_DSN = "your_dev_sentry_dsn_here", REDIS_URL = "your_dev_redis_url_here" }

[context.branch-deploy]
  environment = { NODE_ENV = "development", LOG_LEVEL = "debug", SENTRY_DSN = "your_dev_sentry_dsn_here", REDIS_URL = "your_dev_redis_url_here" }