[build]
  command = "npm run build"
  publish = "dist"
  functions = "dist/functions"

# Cypress E2E tests are currently failing in the build step because the serverless function
# is not yet deployed and accessible when Cypress tries to visit it.
# For E2E tests in CI, consider these approaches:
# 1. Run Cypress as a post-deploy step against the live deployed URL (recommended for true E2E).
# 2. Use `netlify dev` to serve functions locally during CI and point Cypress to `http://localhost:8888`.
# 3. For integration-like tests, mock API responses or use a dedicated test server.

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
