[build]
  command = "cypress install && npm run cypress:run && npm run build"
  publish = "dist"
  functions = "dist/functions"

# TODO: Re-evaluate if Cypress E2E tests are truly necessary during the build phase for every deploy,
# or if they can be run as a separate CI step for faster deploys.

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
