[build]
  command = "cypress install && npm run cypress:run && npm run build"
  publish = "dist"
  functions = "dist/functions"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
