version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: quemiai-postgres
    environment:
      POSTGRES_DB: quemiai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quemiai-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: quemiai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - quemiai-network

  # Backend API
  backend:
    build:
      context: ./apps/backend
      dockerfile: ../../infrastructure/docker/Dockerfile.backend
    container_name: quemiai-backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/quemiai
      REDIS_URL: redis://redis:6379
      NODE_ENV: production
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
    networks:
      - quemiai-network
    restart: unless-stopped

  # Web Application
  web:
    build:
      context: ./apps/web
      dockerfile: ../../infrastructure/docker/Dockerfile.web
    container_name: quemiai-web
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - quemiai-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  quemiai-network:
    driver: bridge
